# Generated by Django 3.2.4 on 2021-06-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_destination_auther'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('disc', models.TextField()),
            ],
        ),
    ]
